create table agenda (fk_usuario integer, id_agenda integer not null auto_increment, primary key (id_agenda)) engine=InnoDB;
create table agendamento (fk_agenda integer, fk_cliente integer, fk_servico integer, id_agendamento integer not null auto_increment, data_hora datetime(6), status_agendamento enum ('AGENDADO','CANCELADO','PENDENTE','REALIZADO'), primary key (id_agendamento)) engine=InnoDB;
create table categoria (id_categoria integer not null auto_increment, nome varchar(255), primary key (id_categoria)) engine=InnoDB;
create table cliente (data_criacao date, data_nascimento date, fk_empresa integer, id_pessoa integer not null auto_increment, email_pessoa varchar(255) not null, genero varchar(255), nome_pessoa varchar(255) not null, numero_telefone varchar(255), senha varchar(255), status_atividade enum ('ATIVO','INATIVO'), primary key (id_pessoa)) engine=InnoDB;
create table empresa (fk_categoria integer, fk_endereco integer, fk_notificacao integer, id_empresa integer not null auto_increment, cnpj varchar(255), email_empresa varchar(255), nome_empresa varchar(255) not null, telefone varchar(255) not null, url_logo varchar(255), primary key (id_empresa)) engine=InnoDB;
create table endereco (id_endereco integer not null auto_increment, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), estado varchar(255), latitude varchar(255), longitude varchar(255), logradouro varchar(255), numero varchar(255), primary key (id_endereco)) engine=InnoDB;
create table funcao (id_funcao integer not null auto_increment, nome_funcao varchar(255), primary key (id_funcao)) engine=InnoDB;
create table imagem (fk_empresa integer, id_imagem integer not null auto_increment, url_imagem varchar(255), primary key (id_imagem)) engine=InnoDB;
create table notificacao (id_notificacao integer not null auto_increment, mensagem_agendamento varchar(255), mensagem_cancelamento varchar(255), primary key (id_notificacao)) engine=InnoDB;
create table servico (duracao time(6), fk_empresa integer, id_servico integer not null auto_increment, valor_servico float(53) not null, nome_servico varchar(100) not null, cor_referencia_hex varchar(255), descricao varchar(255) not null, status_atividade enum ('ATIVO','INATIVO'), primary key (id_servico)) engine=InnoDB;
create table usuarios (data_criacao date, fk_empresa integer, fk_endereco integer, fk_funcao integer, id_pessoa integer not null auto_increment, representante bit, tipos_de_usuario tinyint, cpf varchar(255), email_pessoa varchar(255) not null, firebase_uid varchar(255), nome_pessoa varchar(255) not null, numero_telefone varchar(255), senha varchar(255), status_atividade enum ('ATIVO','INATIVO'), primary key (id_pessoa)) engine=InnoDB;
alter table agenda add constraint UK1025tcbpk6lwew2rmt7cbg8cb unique (fk_usuario);
alter table empresa add constraint UKc1dkodjtoh1ylhd0u0vui7cld unique (fk_endereco);
alter table empresa add constraint UK1pxgbge0ept9nffrrfxrtp4j5 unique (fk_notificacao);
alter table agenda add constraint FK16ualpp3hrardg2kq20kdpyk9 foreign key (fk_usuario) references usuarios (id_pessoa);
alter table agendamento add constraint FKn1aauegeud100luxa5c362ecg foreign key (fk_agenda) references agenda (id_agenda);
alter table agendamento add constraint FKpfdy6wm4v99l9ev51uiuop87e foreign key (fk_cliente) references cliente (id_pessoa);
alter table agendamento add constraint FK3mwegbewvx1xlnnfi4navbssc foreign key (fk_servico) references servico (id_servico);
alter table cliente add constraint FKaj8ittaw6xd5tekg8i38h1qrp foreign key (fk_empresa) references empresa (id_empresa);
alter table empresa add constraint FK2ryb0eos8l0x4ddrogevjyjaa foreign key (fk_categoria) references categoria (id_categoria);
alter table empresa add constraint FK8ison7iq23fgltyioh85skkf6 foreign key (fk_endereco) references endereco (id_endereco);
alter table empresa add constraint FKi9clr71j1raietnhbrho9nxbx foreign key (fk_notificacao) references notificacao (id_notificacao);
alter table imagem add constraint FKsogp8cifrwlfbm0dklksq5raw foreign key (fk_empresa) references empresa (id_empresa);
alter table servico add constraint FKpklckmje05q0y0gltv0elk0bx foreign key (fk_empresa) references empresa (id_empresa);
alter table usuarios add constraint FKrlhx9a6q0wjhs8v18oul9bivt foreign key (fk_empresa) references empresa (id_empresa);
alter table usuarios add constraint FK5aj8h38qs5t8erfeu8n6uka9d foreign key (fk_endereco) references endereco (id_endereco);
alter table usuarios add constraint FK2aldhbmox2b14ud2ugewg5epl foreign key (fk_funcao) references funcao (id_funcao);